In [12]:
import numpy as np

In [13]:
ar1=np.array([1,2,4,5]) 

In [14]:
ar2=np.array([5,2,4,3])

In [15]:
arrnew=ar1+ar2

In [16]:
print(arrnew)

[6 4 8 8]


In [17]:
arrnew=ar1*ar2

In [18]:
print(arrnew)

[ 5  4 16 15]


In [19]:
ar1.ndim

1

two_dimendion =np.array([[1,2,3,4,5][2,3,4,5,6]])

In [35]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2])
print(arr[1,-1])
print(arr[1,-3
          :-1])

8
10
[8 9]


In [45]:
new_arrr1=np.array([1,23,4,4],dtype='S')
print(new_arrr1.astype(bool))
newarr_2=new_arrr1.copy()
print(newarr_2)
x=newarr_2.view()
print(x[0])
x[1]=2
print(x)



[ True  True  True  True]
[b'1' b'23' b'4' b'4']
b'1'
[b'1' b'2' b'4' b'4']


In [36]:
three_dime=np.array([1,2,3,4],ndmin=3)
print(three_dime)
print(three_dime[0,0,1]+three_dime[0,0,3])
print(three_dime.dtype)

[[[1 2 3 4]]]
6
int32


In [20]:
np.__version__

'1.26.4'

In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::-4]):
  print(x)

4
8


In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [71]:
import numpy as np

new_thread_array = np.array([[[[2, 3, 4, 5, 6, 7, 9], [5, 6, 6, 9, 4,8,10]]]])

for x in np.nditer(new_thread_array):
    print(x)


2
3
4
5
6
7
9
5
6
6
9
4
8
10


In [66]:
my_new_arr=np.array([1,2,3,3,4,4,4,45,344,44])
# print(my_new_arr.shape)
nr_r=my_new_arr.reshape(2,5)
print(nr_r)
for x in nr_r:
    for y in x:
        print(y)


[[  1   2   3   3   4]
 [  4   4  45 344  44]]
1
2
3
3
4
4
4
45
344
44


In [10]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [14]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 != 0)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [22]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [24]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [23]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [25]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [26]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [27]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [28]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [48]:
print(three_dime.shape)

[[[1 2 3 4]]]
